### ISSUE TITLE
Color Changes

### ISSUE THREAD

**Issue by NChag** [alex-johnson24/chaggarcharts#30]
Lets make changes to some of the color schemes on here: 

1. I mocked up the yellow for artist, I think it looks good. 
![image](https://user-images.githubusercontent.com/91561870/157887697-d0780ba3-e9e9-40b8-a4b6-524052fcb785.png)

2. Not sure if we wanna go to lighter grey here but very hard to read all of these. 
![image](https://user-images.githubusercontent.com/91561870/157887859-481d35a8-331f-47ad-85ef-662159ea33fd.png)

3. More grey on the login screen but also the blue with auto fills. 
![image](https://user-images.githubusercontent.com/91561870/157888147-e2eaf53c-5c37-409e-a2f4-11005ca8aeea.png)

**Comment by NChag** [comment]
One more on the song submission window. 
![image](https://user-images.githubusercontent.com/91561870/157888714-662491a4-9c2b-49ad-be05-e0afe1ea72c3.png)

**Comment by dougschurman** [comment]
Number 2 is already finished  via the latest commit, for number 1, last commit I change the color to a light gray, we can't change it to yellow without making the light version green, else I can import the theme context and use an if statement if we want to dirty up the code a little bit. Number 3 fixed the buttons at the bottom for both adding a song and the existing song dialog.
